### ISSUE TITLE
3D test update

### ISSUE THREAD

**Issue by ikhsan017** [f-abuleux/3d_test_three.js#1]
Selamat sore mas @f-abuleux , terima kasih sudah submit teknikal test, tapi karena ada sedikit kesalahan dari pihak kami, bisa kah hasil testnya di update sesuai dengan 'expected result' yang baru?

![image](https://github.com/user-attachments/assets/75eee85d-23a6-495f-8e7e-b16a23b02472)

**Comment by f-abuleux** [comment]
Selamat sore pak Ikhsan baik akan saya update. Kalau boleh tau apakah
anglenya harus 100% akurat ?

Terimakasih.

**Comment by ikhsan017** [comment]
angle tidak harus sesuai, karena sudah ada camera control

**Comment by f-abuleux** [comment]
ohiya baik kalau begitu. terima kasih.

**Comment by f-abuleux** [comment]
Selamat pagi pak Ikhsan sudah saya update dengan expected result yang ke 2 tetapi apakah memang benar pada ss yang saya kirimkan lingkaran 1 gapnya 0.02m dan linkaran 2 gapnya 0.54m? push terakhir mengikuti perhitungan saat ini. Terima kasih.

![Screenshot 2024-12-26 100234](https://github.com/user-attachments/assets/ddd44f70-c36b-4ce0-9fde-2ce759cb5566)

**Comment by ikhsan017** [comment]
siang mas @f-abuleux , yg di gambar hanya ilustrasi, maksud saya, update tasknya adalah ikut serta menampilkan text-text anotasi tersebut ke hasil akhir, bukan update position sesuai text di gambar

**Comment by f-abuleux** [comment]
Siang pak , ohokay baik pak.

**Comment by f-abuleux** [comment]
Selamat malam pak, Izin bertanya apakah tidak oke ketika dia masih mengikuti pov . Terima kasih.
![Screenshot 2024-12-26 192728](https://github.com/user-attachments/assets/bd0aa574-9cf2-4b8f-9773-f68cc7b0b4e8)

**Comment by ikhsan017** [comment]
ok mas @f-abuleux
